name: Publish API Documentation

on:
  workflow_dispatch:

jobs:
  publish-apidocs:
    name: Publish API Documentation
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Build API Documentation
        id: build-apidocs
        run: |
          $MVN -D quickly clean install
          $MVN -P snippets javadoc:aggregate
          $MVN -P snippets javadoc:javadoc
          $MVN -P snippets org.apache.maven.plugins:maven-antrun-plugin:run@copy-apidocs
      - name: Publish API Documentation
        id: publish-apidocs
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          repository-name: patternfly-java/apidocs
          token: ${{ secrets.PUBLISH_CONTENT }}
          branch: main
          folder: ./target/site/apidocs
          clean: true
