name: Publish Showcase

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Showcase
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Build Showcase
        id: build-showcase
        run: $MVN --projects org.patternfly:patternfly-java-showcase-dist --also-make -P showcase,prod package
      - name: Publish Showcase
        id: publish-samples
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: ./showcase/dist/target/showcase
          target-folder: showcase
          clean: true
