name: Release PatternFly Java

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy Maven Artifacts
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Package
        id: package
        run: $MVN package
      - name: Set up Maven Settings
        id: setup-maven-settings
        uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          java-version: 11
          distribution: temurin
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy
        id: deploy
        run: $MVN deploy -P release
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Install
        id: install
        run: $MVN -D quickly install
      - name: Build API Documentation
        id: build-api-docs
        run: ./javadoc.sh
      - name: Publish API Documentation
        id: publish-api-docs
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: ./target/site/apidocs
          target-folder: apidocs
          clean: true
      - name: Build Showcase
        id: build-showcase
        run: $MVN --projects org.patternfly:patternfly-java-showcase-dist --also-make -P showcase,prod package
      - name: Publish Samples
        id: publish-samples
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: ./showcase/dist/target/showcase
          target-folder: showcase
          clean: true

  release:
    name: Create GitHub Release
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: get-version
        uses: battila7/get-version-action@v2.3.0
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Read Changelog
        id: read-changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./CHANGELOG.md
          version: ${{ steps.get-version.outputs.version-without-v }}
      - name: Create GitHub Release
        id: create-gh-release
        uses: softprops/action-gh-release@v2.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          name: PatternFly Java ${{ steps.get-version.outputs.version-without-v }}
          body: ${{ steps.read-changelog.outputs.changes }}
          draft: false
          prerelease: false
          discussion_category_name: announcements
